[package]
name = "resume_stats"
version = "0.1.0"
edition = "2024"

[dependencies]
octocrab = "0.44.0"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.1", features = ["full"] }
toml = "0.8.20"
